### ISSUE TITLE
Using boost::asio buffer as argument in mocked function fails with VS2019

### ISSUE THREAD

**Issue by laudrup** [rollbear/trompeloeil#174] opened 2019-12-22 15:54 UTC
I'm attempting to mock out some boost::asio functions and the following fails to compile with Visual Studio 2019:

```
struct interface {
  virtual void do_stuff(const boost::asio::const_buffer&) = 0;
};

struct impl : public interface {
  MAKE_MOCK1(do_stuff, void(const boost::asio::const_buffer&), override);
};
```

with:
```
binary '==': 'const Executor' does not define this operator or a conversion to  a type acceptable to the predefined operator [C:\build\ping\test.vcxproj]
          with
          [
              Executor=boost::asio::const_buffer
          ]
```
As far as I can tell, trompeloeils SFINAE magic detects that the `boost::asio::const_buffer` can be compared to a `std::nullptr_t` and for some reason then requires `boost::asio::const_buffer` to have a comparison operator (which it doesn't).

What makes this more strange is, that it works just fine with GCC and Clang and what makes it even more strange is, that I haven't been able to reproduce this by making my own type/class that should behave the same way as `boost::asio::const_buffer` in that regard.

As a workaround, specializing trompeloeils `is_null()` function works:

```
namespace trompeloeil {
bool is_null(const boost::asio::const_buffer&) {
  return false;
}
}
```

I wish I could give a better reproducable example, but unfortunately haven't been able to.

I guess this could be a bug in MSVC2019 (possibly earlier versions as well), but to be honest, I'm not really sure what is going on here.

If you need any more input from me or some patches I should try out, please let me know. I'm a bit lost here to be honest.

Thanks a lot, kind regards and "god jul".

**Comment by rollbear** [comment] 2019-12-22 16:01
You may want to try latest on `master`. Earlier today I pushed fixes for a very similar problem.

**Comment by laudrup** [comment] 2019-12-22 16:20
Just tried that, unfortunately still the same problem :-(

**Comment by rollbear** [comment] 2019-12-23 09:09
OK, thanks. It was worth a shot. I'll look into it.

**Comment by rollbear** [comment] 2019-12-23 09:24
I am very confused now. I can't reproduce locally, but then I don't have Windows on my laptop. I tried to use compiler explorer, and it compiles your example:

https://godbolt.org/z/DYoHYy

Which version of boost? Which version of MSVC and which compilation flags?

**Comment by laudrup** [comment] 2019-12-25 16:53
This is really weird indeed.

I don't normally use Windows either, but I was running this in a virtual machine with Windows 10, using the latest version of Visual Studio 2019 and pretty much a "vanilla" CMake configuration (ie. no extra compiler flags).

I experienced the issue with Boost 1.72, but it's the same issue with Boost 1.71.

I've also experimented a bit with building boost with different options, but as boost::asio is header only  that should make any difference (but might change the install target, so I thought it was worth a try).

So I cannot really see how my configuration is any different from that of Compiler Explorer, but I must admit I don't have much experience with Windows development.

This is most likely not an issue with trompeloeil after all (although I hope you can forgive me for assuming it was), but it annoys me a bit that I cannot figure out what causes this.

I'll try to see if I can figure out what might cause this and if not, close this issue.

**Comment by rollbear** [comment] 2019-12-29 11:13
OK, closing now. Feel free to reopen if you stumble upon it again.

**Closed by rollbear** 2019-12-29 11:13 UTC
