### ISSUE TITLE
doctest: Trompeloeil error reporting via doctest/trompeloeil.hpp gives unhelpful output

### ISSUE THREAD

**Issue by SimonKagstrom** [rollbear/trompeloeil#279] opened 2022-09-12 12:33 UTC
Environment: Trompeloeil v42, doctest v2.4.9 from conan packages. G++-11

When a trompeloeil expectation fails, doctest only reports an address, which makes it harder to understand what the actual error was:

```[doctest] doctest version is "2.4.9"
[doctest] run with "--help" for options
===============================================================================
/tmp/trompeloeil_test.cpp:46:
  Scenario: trompeloeil + doctest error reporting works

/tmp/trompeloeil_test.cpp:50: ERROR: 0x55af94acfb20

===============================================================================
[doctest] test cases: 1 | 0 passed | 1 failed | 0 skipped
[doctest] assertions: 1 | 0 passed | 1 failed |
[doctest] Status: FAILURE!
```

A test program to reproduce this is:

```
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"
#include "doctest/trompeloeil.hpp"

class Test
{
public:
    MAKE_MOCK0(x, void());
};

SCENARIO("trompeloeil + doctest error reporting works")
{
    Test t;

    REQUIRE_CALL(t, x());
}
```

And the problem can be fixed by passing a std::string to `DOCTEST_ADD_FAIL_MESSAGE` from `reporter<specialized>::send()`:

```
      DOCTEST_ADD_FAIL_CHECK_AT(f, line, std::string(msg));
```

**Comment by rollbear** [comment] 2022-09-13 08:21
Interesting. This seems to be caused by a change in `doctest`. The same in `2.3.8` works.

https://godbolt.org/z/31czP6hTo

I'll look into it. Thanks.

**Comment by rollbear** [comment] 2022-09-13 09:19
Can you try with the branch [fix_doctest_adapter](https://github.com/rollbear/trompeloeil/tree/fix_doctest_adapter), which I think should solve your problem?

**Comment by SimonKagstrom** [comment] 2022-09-13 10:54
Works fine!

```
[doctest] doctest version is "2.4.9"
[doctest] run with "--help" for options
===============================================================================
/tmp/trompeloeil_test.cpp:12:
  Scenario: trompeloeil + doctest error reporting works

/tmp/trompeloeil_test.cpp:16: ERROR: Unfulfilled expectation:
Expected t.x() to be called once, actually never called


===============================================================================
[doctest] test cases: 1 | 0 passed | 1 failed | 0 skipped
[doctest] assertions: 1 | 0 passed | 1 failed |
[doctest] Status: FAILURE!
```

**Comment by rollbear** [comment] 2022-09-13 14:55
Ops. Fixed.

Leaving this open until a release has been tagged.

**Comment by rollbear** [comment] 2022-10-26 10:19
Just released v43 which includes this fix. Closing now.

**Closed by rollbear** 2022-10-26 10:19 UTC
Labels: Fixed on main
