### ISSUE TITLE
BUG trompeloeil is not using semver

### ISSUE THREAD

**Issue by blackliner** [rollbear/trompeloeil#222] opened 2020-12-15 12:18 UTC
trompeloeil should convert to using semantic versioning instead of the `v39`-style.

Why? CMake does not support `find_package(trompeloeil v39 REQUIRED)`

**Comment by rollbear** [comment] 2020-12-15 13:35
No, it should not. It's a fundamentally broken idea. But, I will update the doc so that others won't have to make the same mistake.

`find_package(trompeloeil 39 REQUIRED)` works fine. Thank you for reporting the problem.

**Comment by blackliner** [comment] 2020-12-15 13:50
Your proposed solution does not work, I tried it. Here is the errorlog:
```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find trompeloeil: Found unsuitable version "v39", but required is
  at least "39" (found v39)
```

**Comment by rollbear** [comment] 2020-12-15 13:52
Hmm, that is weird. It worked here a minute before I responded. I'll see if I can reproduce so that I can understand what's happening.

**Comment by blackliner** [comment] 2020-12-15 13:56
teeeeeeeeny tiny hint: I am using CMake 3.10 and conan for providing trombleioiloiel

**Comment by rollbear** [comment] 2020-12-15 13:59
Thank you

**Comment by blackliner** [comment] 2020-12-15 14:12
I previously used the CCI version of the conan trompeloeil package. Maybe the `conanfile.py` from this repo works better, but unfortunately it specifies `set(trompeloeil_VERSION "v39")` as well.

So TL&DR: `conan` with `generators = "cmake_find_package"` and `trompeloeil` do not support modern CMake 😞

**Comment by rollbear** [comment] 2020-12-15 14:12
It's probably conan that gets confused. It looks like it is indeed a mistake to have the 'v' in the conan version name, as you suggested.

**Comment by blackliner** [comment] 2020-12-15 14:21
Yes, with this change it works. Changing the `version = v39` to `version = 39` in the `conanfile.py` and running `conan create . trompeloeil/39@` (instead of `conan create . trompeloeil/v39@`) works! 🎉 

autogenerated `Findtrompeloeil.cmake` now contains
```
set(trompeloeil_VERSION "39")
```

result using `find_package(trompeloeil 39 REQUIRED)`:
```
-- Found trompeloeil: 39 (found suitable version "39", minimum required is "39")
```

**Comment by rollbear** [comment] 2020-12-15 14:22
Excellent! Thank you. Currently a bit busy doing the kind of work that pays bills, but I'll get back to this shortly.

**Comment by blackliner** [comment] 2020-12-15 14:23
Additional question: What is the reason for having the `conanfile.py` stored in your repo instead of providing it for CCI? I am honestly interested in the reasons why this could be an advantage. If you just dont have the time to do it in CCI, I could take a smack at it? Because currently (and unfortunately), trompeloeil is marked as a legacy package (???) on conan center 😞 https://conan.io/center/trompeloeil
![image](https://user-images.githubusercontent.com/23190927/102227144-84212980-3ee9-11eb-81b0-b2b6a07f739b.png)

**Comment by rollbear** [comment] 2020-12-15 14:25
Only because it's old. CCI did not exist at the time. There is a bug report #220 that brings up exactly that point.

**Comment by blackliner** [comment] 2020-12-15 15:37
https://github.com/conan-io/conan-center-index/pull/3901

**Comment by rollbear** [comment] 2020-12-16 06:38
Thank you for this!

**Comment by blackliner** [comment] 2020-12-22 15:31
Its merged 👍 https://conan.io/center/trompeloeil

![image](https://user-images.githubusercontent.com/23190927/102905280-2ce40180-4473-11eb-990f-d80b07a8cc0b.png)

**Comment by blackliner** [comment] 2020-12-23 16:26
You can keep it open if you consider to ever move to semver, if not, I got what I needed 😄

**Comment by rollbear** [comment] 2020-12-23 17:06
I'm going to make the doc update I promised, then I can close it. Thank you so very much for doing this for me. Remind me to buy you a beer, should we ever meet. 🍺

**Comment by blackliner** [comment] 2020-12-23 20:29
Haha, will do as soon as the whole world is accessible again 👍

**Comment by rollbear** [comment] 2020-12-27 12:27
Doing the cleaning up now. Just to make sure I don't cause trouble, I should be able to remove the local conanfile.py, and the CI conan test builds, right? The conan recipe on conan-center is stand-alone and does not need this support.

**Comment by blackliner** [comment] 2020-12-28 09:51
Yes, you can safely remove everything conan related from your repo if you like.

**Comment by rollbear** [comment] 2021-01-22 20:48
All gone now.

**Closed by rollbear** 2021-01-22 20:48 UTC
