### ISSUE TITLE
Mis-spelled preprocessor symbol TROMPELOEIL_GCC_VERSION

### ISSUE THREAD

**Issue by AndrewPaxie** [rollbear/trompeloeil#298] opened 2023-04-10 21:30 UTC
In version 44 of Trompeloeil, there is a mis-spelling of the preprocessor symbol `TROMPELOEIL_GCC_VERSION` on lines 4023 and 4026.

The effect is to disable the `-Wconversion` warning for all versions of the GCC compiler greater than or equal to 7.0.0, when perhaps a more restricted range was desired.

**Comment by rollbear** [comment] 2023-04-11 13:26
Fixed now. The problem is really only for gcc-7 and only when building as C++17. Very odd. I have not bothered restricting this section to C++17 only. Thanks for reporting!

**Closed by rollbear** 2023-04-11 13:26 UTC
