### ISSUE TITLE
[fixed on master] MSVC 2015 compatibility

### ISSUE THREAD

**Issue by Neargye** [rollbear/trompeloeil#82] opened 2018-05-02 21:53 UTC
Version 30 in MSVC 2015 build fail.
Full report can be seen [here](https://ci.appveyor.com/project/Neargye/trompeloeil/build/msvc_cpp14%20%234)or https://github.com/rollbear/trompeloeil/pull/81

**Comment by Neargye** [comment] 2018-05-02 22:34
[appveyor.yml ](https://github.com/rollbear/trompeloeil/files/1969112/appveyor.zip) with tet on VS2015/VS2017 x32/x64

**Comment by Neargye** [comment] 2018-05-02 22:48
I thought for cross-platform rewrite tests and compilation_tests(compilation_errors) to cmake ctest and 
 cmake try_compile

**Comment by AndrewPaxie** [comment] 2018-05-03 10:46
I have a proposed change that has been tested on all supported platforms **except**
VS2015.  Will bring AppVeyor support up in the same pull request, which is in progress.

**Comment by Neargye** [comment] 2018-05-03 16:42
It's still fail build
```

**Comment by Neargye** [comment] 2018-05-03 16:50
if change compiling_tests.hpp(190)
```cpp
struct mi : interface //trompeloeil::mock_interface<interface>
{
  //using mock_interface::mock_interface;
  //IMPLEMENT_MOCK1(func);
  //IMPLEMENT_CONST_MOCK1(cfunc);
  //IMPLEMENT_MOCK3(func3);
  //IMPLEMENT_CONST_MOCK3(func3);
  MAKE_MOCK1(func, int(int), override);
  MAKE_CONST_MOCK1(cfunc, int(int), override);
  MAKE_MOCK3(func3, int(int, int, std::string), override);
  MAKE_CONST_MOCK3(func3, int(int, int, std::string), override);
};
```
build succes

**Comment by AndrewPaxie** [comment] 2018-05-03 19:06
OK, looks like we tripped ourselves up with the implementation of #73.

**Comment by AndrewPaxie** [comment] 2018-05-04 12:29
OK, looks like we tripped ourselves up with the implementation of #73.

**Comment by AndrewPaxie** [comment] 2018-05-05 06:31
I will work to get this bug fixed on master sooner than the support for AppVeyor,
which I have raised as issue #83.

**Comment by rollbear** [comment] 2018-05-05 07:33
Great news! I'm really confused by the 2nd commit, though. I don't understand why it makes any difference. I assume this is a work around for an MSVC 2015 bug? Is that bug reported? I try to document compiler bug work arounds in comments, since these are always confusing constructions (although sometimes I forget.)

Regardless, I think this calls for a new release tag, as a bugfix (or maybe wait until appveyor integration is also done)?

**Comment by AndrewPaxie** [comment] 2018-05-05 08:44
Recognizing this is a bugfix lead me to separate the AppVeyor support,
since it has an unknown time to completion
(actual sample implementation notwithstanding).
Hence #83.
I am in the process of regression testing a patch against master.

I isolated the VS 2015 issue by pasted the preprocessed output from a `clang++-6.0`
command into <http://rextester.com/l/cpp_online_compiler_visual>
and fixing it up enough to see the line number and construct with the error.

The VS 2015 parser falls apart when given a function with a trailing return type that
has a `decltype` that is "complex", i.e. when `sig` is

```cpp
decltype(::trompeloeil::nonconst_member_signature(&trompeloeil_interface_name::func))::type
```

from `IMPLEMENT_MOCK(func)`.

My comment in the code is currently

```cpp
    /* Work around parsing bug in VS 2015 when a "complex" */                  \
    /* decltype() appears in a trailing return type. */                        \
    using trompeloeil_sig_t = sig;                                             \
```

I kind of lack the language to be more precise at the moment, but will work to reduce
the issue to a more reasonable test case.

BTW: What is the official Microsoft defect database for Visual C\+\+?
Initial search reveals it has changed over time.
Is it browsable?

If this was a reported bug then it was fixed in VS 2017, as there is no issue with this compiler.

**Comment by rollbear** [comment] 2018-05-05 08:58
An older bug report referred to this microsoft bug report forum - I don't know if that's the right place to go, though.
https://developercommunity.visualstudio.com/content/problem/25323/internal-error-in-the-compiler-when-building-heavi.html

It's not like I haven't fought with other compilers on complex decltype in trailing return type expressions.
 
I think your comment is good enough. The reason for asking if it's reported is just that I think reporting found compiler bugs is the right thing to do.

**Comment by AndrewPaxie** [comment] 2018-05-05 10:04
I'll follow up on this link.

I agree with the strategy of reporting compiler bugs to those who can fix them.
It's just that I haven't encountered that many that hadn't already been found years ago until
I got involved in this project.  Then - wham! - bleeding edge (and loving it).

Travis is currently building the branch after success locally (including VS 2017).

As far as reducing this issue is concerned I've reached the point where the error
occurs if a trailing return type of required complexity is provided to a member function template,
but no error occurs if the code is trivially transformed to a member function with
trailing return type.  Current best reduced code,

```cpp
// Library code

template <typename T>
struct identity_type
{
  using type = T;
};

template <typename R, typename C, typename ... Args>
identity_type<R(Args...)>
signature(R (C::*)(Args...))
{
  return {};
}

template <typename T>
struct modifier
{
};

template <typename T>
struct mock_interface : public T
{
  using interface_name = T;
  using T::T;
};


// -- Example code

struct interface
{
  virtual ~interface() = default;
  virtual int func(int) = 0;
};

struct mi: mock_interface<interface>
{

  struct tag_type
  {
    template <typename T>
    auto func()
    // FAIL:
    -> modifier<decltype(signature(&interface_name::func))::type>
    // PASS: -> modifier<identity_type<int (int)>::type>
    // PASS: -> decltype(signature(&interface_name::func))
    // FAIL: -> modifier<typename decltype(signature(&interface_name::func))::type>
    // PASS: -> modifier<decltype(signature(&interface_name::func))>
    {
      return {};
    }
  };

};

int main()
{
    return 0;
}
```

@Neargye : I propose that I will make a pull request to `master` after you confirm that
VS 2015 is OK with this latest version of the branch.

**Comment by AndrewPaxie** [comment] 2018-05-05 10:27
@rollbear : <https://developercommunity.visualstudio.com/spaces/62/index.html>
seems to be where Visual Studio issues are posted.  Thanks for the guidance.

**Comment by rollbear** [comment] 2018-05-05 17:36
I'm leaving this open until it's included in a tagged release.

**Comment by rollbear** [comment] 2018-05-12 06:32
Time to close now. Included in latest release.

**Closed by rollbear** 2018-05-12 06:32 UTC
Labels: bug

**Comment by rollbear** [comment] 2018-05-15 13:50
You know they say that if you're not filing compiler bug reports, you're not doing C++ properly ;-)

**Comment by AndrewPaxie** [comment] 2018-05-16 08:55
Filed second VS 2015 compiler problem with Microsoft,
<https://developercommunity.visualstudio.com/content/problem/254369/vc-2015u1-decltype-in-trailing-return-type-parse-e.html>
Unfortunately the report was horribly, horribly mangled by their submission form "system".
Tried to fix it up but to no avail.
