### ISSUE TITLE
terminate called without an active exception

### ISSUE THREAD

**Issue by Hawk777** [rollbear/trompeloeil#155] opened 2019-08-17 04:53 UTC
$ gcc --version
gcc (Gentoo 8.3.0-r1 p1.1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cat test.cpp
#include "include/trompeloeil.hpp"

class C {
	public:
	MAKE_MOCK0(f, void());
};

int main() {
	C obj;
	REQUIRE_CALL(obj, f());
	return 0;
}

$ g++ -Wall -Wextra -O2 -march=native -std=c++17 test.cpp && ./a.out
terminate called without an active exception
Aborted

This is not the result I was expecting. I was expecting the uncalled required call to be reported via an exception, not terminate called without an active exception!

**Comment by rollbear** [comment] 2019-08-17 07:58
Working as designed.

https://github.com/rollbear/trompeloeil/blob/master/docs/FAQ.md#q-how-do-i-use-trompeloeil-with-xxx-unit-test-framework

By default trompeloeil reports all errors by throwing an exception. Checks for unfulfilled expectations are made in the destructor of the expectation object (created by the `REQUIRE_CALL` macro.) Thus an expectation is thrown and you have no catch anywhere, so the program terminates.

**Comment by rollbear** [comment] 2019-08-17 08:04
Interesting. This has something to do with the optimizer. With your program:

```
bf@confuciusornis /tmp> g++ -ggdb -Wall -Wextra  -march=native -std=c++17 t.cpp -I ~/develop/trompeloeil/include
bf@confuciusornis /tmp> ./a.out 
terminate called after throwing an instance of 'trompeloeil::expectation_violation'
  what():  t.cpp:10
Unfulfilled expectation:
Expected obj.f() to be called once, actually never called

fish: Job 2, “./a.out” terminated by signal SIGABRT (Abort)
```

And with -O2

```
bf@confuciusornis /tmp> g++ -ggdb -O2 -Wall -Wextra  -march=native -std=c++17 t.cpp -I ~/develop/trompeloeil/include
bf@confuciusornis /tmp> ./a.out
terminate called without an active exception
fish: Job 2, “./a.out” terminated by signal SIGABRT (Abort)
```

With clang, it also works as expected:

```
bf@confuciusornis /tmp> clang++-8 -ggdb -O3 -Wall -Wextra  -march=native -std=c++17 t.cpp -I ~/develop/trompeloeil/include
bf@confuciusornis /tmp> ./a.out
terminate called after throwing an instance of 'trompeloeil::expectation_violation'
  what():  t.cpp:10
Unfulfilled expectation:
Expected obj.f() to be called once, actually never called

fish: Job 2, “./a.out” terminated by signal SIGABRT (Abort)
```

**Comment by rollbear** [comment] 2019-08-17 08:30
My understanding is that the standard doesn't mandate doing anything other than terminating, when an exception is thrown and there is no handler.

http://eel.is/c++draft/except.terminate#2

gcc and clang both print out information about the exception, though, but for some reason gcc opts out of doing so when optimization is enabled.

**Comment by Hawk777** [comment] 2019-08-17 14:11
When I surround the body of `main` with a `try`/`catch` block, it doesn’t catch anything. I still get the same `terminate called without an active exception` message. I used `catch(...)` so I should have caught literally anything. I was under the impression that the exception was thrown in the destructor of a local variable created by `REQUIRE_CALL`, so by placing `REQUIRE_CALL` inside the `try`, the destructor should have been invoked at the closing brace of the `try` block and therefore the exception be able to be caught?

**Comment by rollbear** [comment] 2019-09-17 15:29
Your impression is correct. The exception is thrown from the destructor of a local variable, and that too is mandated to terminate the program.

http://eel.is/c++draft/except.terminate#1.4

Trompeloeil reports the violation by calling `trompeloeil::reporter<trompeloeil::specialized>::send(...)`. The default implementation of that function always throws. But, the 1st parameter is an enum of type `trompeloeil::severity`, which can have the values `fatal` and `nonfatal`. In this case, the value is `nonfatal`, signaling that it is OK for the program to continue execution. Most unit testing framework adapters make use of this, in the way that most unit testing frameworks have some mechanism of failing a test without throwing. For example, the adapter for the `catch2` unit testing framework, composes a string out of the message, and `CHECK()` that the string is empty. `CHECK()` fails the test without throwing.

It is a pity that gcc chooses to not display the `what()` string of an exception in this situation, for optimized builds. However, by writing an adapter that reports the error in some other way (perhaps even by terminating, but with a message) you'll get adequate feedback for failed tests. See the [CookBook](https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#unit_test_frameworks) for information about writing an adapter.

**Comment by Hawk777** [comment] 2019-09-18 02:55
That spec sentence you quoted says this:
> when the destruction of an object during stack unwinding terminates by throwing an exception, or

but “stack unwinding” is a link to the exception handling section, which states that:
> As control passes from the point where an exception is thrown to a handler, objects with automatic storage duration are destroyed by a process, specified in this subclause, called stack unwinding.

So it seems like “stack unwinding” refers specifically to unwinding the stack during an exception throw. That’s the rule I already knew about C++: you can’t throw an exception from a destructor of an object that’s being called because another exception is already active. But it seems like that’s not what’s happening here, is it? The issue here is an exception being thrown during a normal function return, *not* during an exception throw, which AFAICT doesn’t invoke this clause and ought to be OK?

**Comment by rollbear** [comment] 2019-09-18 04:12
https://godbolt.org/z/7RSGyR

**Comment by rollbear** [comment] 2019-09-18 04:18
So, yes. The compiler seems to agree with you. I don't know what's happening here. Will investigate closer.

**Comment by rollbear** [comment] 2019-09-18 07:40
I kind of understand now, but only kind of. If you use a compile time reporter which throws, then all is fine. If you use a run time reporter (which is the default, for historical reasons) gcc gives the behaviour you've reported.

The real error is that a bunch of destructors should be `noexcept(false)`, but I cannot make that change now, since it's a breaking change affecting user code.

As a work-around, I've experimented with the following simple change:

```diff
diff --git a/include/trompeloeil.hpp b/include/trompeloeil.hpp
index a22190b..c08c7ac 100644
--- a/include/trompeloeil.hpp
+++ b/include/trompeloeil.hpp
@@ -3669,6 +3669,7 @@ template <typename T>
     void
     report_missed(
       char const *reason)
+    noexcept
     {
       reported = true;
       report_unfulfilled(
```

My understanding is that this makes the compiler effectively generate code like:

```Cpp
void report_missed(char const* reason)
{
  try {
    ...
  }
  catch (...) {
    error_message(*std::current_exception());
    std::terminate();
  }
}
```

I then get the message, regardless of optimization level.

**Comment by Hawk777** [comment] 2019-09-18 14:27
Right, right, I forgot that C++11 made destructors `noexcept` by default. Eh, it’s a bit nasty, but I suppose it works (it does for me anyway). And I guess since destructors are `noexcept` by default, to do it the “proper” way would go all the way to requiring all the user’s classes to have `noexcept(false)` destructors, which wouldn’t really work with the fact that all Trompeloeil’s macros are invoked once per member function, so there’s no where to put a destructor of which there must be only one per class.

**Comment by rollbear** [comment] 2019-09-19 07:02
I just pushed the above fix to `master`. It still terminates, but at least it terminates with the expected violation messages. I don't think a full solution is possible.

Leaving the issue open until the fix is included in a tagged release.

**Comment by rollbear** [comment] 2019-09-24 15:21
Fixed in release v35. Closing.

**Closed by rollbear** 2019-09-24 15:21 UTC
Labels: Fixed on master
