### ISSUE TITLE
How to mock a member function with QtJsonObject parameter

### ISSUE THREAD

**Issue by evelynpenacc** [rollbear/trompeloeil#113] opened 2019-01-18 22:44 UTC
I have an issue when I attempt to mock a member function that has as parameter a Qt type "QJsonObject".
I have an Interface defined as follow:
`class ILiteServiceInfoMessageHandler{
public:
    virtual ~ILiteServiceInfoMessageHandler(){};
    virtual void processMessage(QJsonObject messageObj) = 0;
};`
and a class that implements that interface:
`LiteServiceInfoMessageHandler:public QObject, public ILiteServiceInfoMessageHandler
{
    Q_OBJECT
    Q_INTERFACES(ILiteServiceInfoMessageHandler)
public:
 .........................
void processMessage(QJsonObject messageObj);
}`
in my uni test 
`#include <trompeloeil.hpp>
extern template struct trompeloeil::reporter<trompeloeil::specialized>;

class LiteServiceInfoMessageHandlerMock: public LiteServiceInfoMessageHandler{
public:
    MAKE_MOCK0(requestInitialData,void(),override);//works fine
    MAKE_MOCK1(processMessage,void(QJsonObject),override);//throw compilation error
}

SECTION("onReceive Base Page Items Method") {
        QJsonObject messageAction = {
            {MESSAGE_KEY_MESSAGE_TYPE,BASE_PAGE_ITEMS_METHOD},
            {MESSAGE_KEY_CALLER_ID,callerId}
        };
        QJsonObject messageObj={
            {NOTIFY_ACTION,SERVER_MESSAGE},
            {USER_INFO,messageAction}
        };
        REQUIRE_CALL(liteServiceInfoHandlerMock,processMessage(messageObj));
        liteServiceInfoHandlerMock.setMessageHandlerTypeList();
        liteServiceInfoHandlerMock.onReceive(messageObj);
    }
`
______________________________________________________________________________________________________
This is the stack trace of the error:
In file included from ../tests/tst_testliteserviceinfomessagehandler.cpp:2:
../3rdparty/trompeloeil/trompeloeil.hpp:1189:18: error: non-const lvalue reference to type 'QJsonValue' cannot bind to a temporary of type 'QJsonValue'
      for (auto& elem : t)
                 ^    ~
../3rdparty/trompeloeil/trompeloeil.hpp:1235:20: note: in instantiation of member function 'trompeloeil::streamer<QJsonObject, false, true>::print' requested here
      streamer<T>::print(os, t);
                   ^
../3rdparty/trompeloeil/trompeloeil.hpp:2809:20: note: in instantiation of function template specialization 'trompeloeil::print<QJsonObject>' requested here
    ::trompeloeil::print(os, t);
                   ^
../3rdparty/trompeloeil/trompeloeil.hpp:2820:55: note: in instantiation of function template specialization 'trompeloeil::missed_value<QJsonObject>' requested here
    ::trompeloeil::ignore(std::initializer_list<int>{(missed_value(os, I, std::get<I>(t)),0)...});
                                                      ^
../3rdparty/trompeloeil/trompeloeil.hpp:2829:5: note: in instantiation of function template specialization 'trompeloeil::stream_params<0, QJsonObject &>' requested here
    stream_params(os, detail::make_index_sequence<sizeof...(T)>{}, t);
    ^
../3rdparty/trompeloeil/trompeloeil.hpp:2962:5: note: in instantiation of function template specialization 'trompeloeil::stream_params<QJsonObject &>' requested here
    stream_params(os, p);
    ^
../3rdparty/trompeloeil/trompeloeil.hpp:3890:7: note: in instantiation of function template specialization 'trompeloeil::report_mismatch<void (QJsonObject)>' requested here
      report_mismatch(e.active,
      ^
../tests/tst_testliteserviceinfomessagehandler.cpp:19:5: note: in instantiation of function template specialization 'trompeloeil::mock_func<void (QJsonObject), QJsonObject &>' requested here
    MAKE_MOCK1(processMessage,void(QJsonObject),override);
    ^
../3rdparty/trompeloeil/trompeloeil.hpp:4747:35: note: expanded from macro 'MAKE_MOCK1'
#define MAKE_MOCK1                TROMPELOEIL_MAKE_MOCK1
                                  ^
../3rdparty/trompeloeil/trompeloeil.hpp:4050:3: note: expanded from macro 'TROMPELOEIL_MAKE_MOCK1'
  TROMPELOEIL_MAKE_MOCK_(name,,1, __VA_ARGS__,,)
  ^
../3rdparty/trompeloeil/trompeloeil.hpp:4259:27: note: expanded from macro 'TROMPELOEIL_MAKE_MOCK_'
    return ::trompeloeil::mock_func<sig>(TROMPELOEIL_LINE_ID(cardinality_match){},  \
                          ^
/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qjsonobject.h:215:27: note: selected 'begin' function with iterator type 'QJsonObject::const_iterator'
    inline const_iterator begin() const { return const_iterator(this, 0); }
                          ^
1 error generated.
make: *** [tst_testliteserviceinfomessagehandler.o] Error 1

**Comment by rollbear** [comment] 2019-01-19 07:12
Oh, I think I see the bug. Can you, as an experiment, try to change line trompeloeil.hpp:1189 to read:

```Cpp
      for (auto const& elem : t)
```

(added the `const`).

**Comment by rollbear** [comment] 2019-01-19 08:32
Pushed a fix for what I believe is the same bug. Leaving the issue open until I tag a release (probably this weekend.)

**Comment by evelynpenacc** [comment] 2019-01-20 00:40
Well now that i had test the change my previous test are falling:
`LiteServiceInfoMessageHandler
  onReceive UI Refresh Required
-------------------------------------------------------------------------------
../tests/tst_testliteserviceinfomessagehandler.cpp:68
...............................................................................

../3rdparty/trompeloeil/trompeloeil_catch.hpp:21: FAILED:
explicitly with message:
  No match for call of processMessage with signature void(QJsonObject) with.
    param  _1 == { 24-byte object={
   0x20 0xae 0x57 0x99 0xba 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 }, 24-byte object={
   0x20 0xae 0x57 0x99 0xba 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 } }

../3rdparty/trompeloeil/trompeloeil_catch.hpp:26: FAILED:
  CHECK( failure.empty() )
with expansion:
  false
with message:
  failure := "../tests/tst_testliteserviceinfomessagehandler.cpp:69
  Unfulfilled expectation:
  Expected liteServiceInfoHandlerMock.requestInitialData() to be called once,
  actually never called
  "

-------------------------------------------------------------------------------
LiteServiceInfoMessageHandler
  onReceive unhandled message
-------------------------------------------------------------------------------
../tests/tst_testliteserviceinfomessagehandler.cpp:82
...............................................................................

../3rdparty/trompeloeil/trompeloeil_catch.hpp:21: FAILED:
explicitly with message:
  No match for call of processMessage with signature void(QJsonObject) with.
    param  _1 == { 24-byte object={
   0x00 0xba 0x57 0x99 0xba 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 }, 24-byte object={
   0x70 0xc6 0x57 0x99 0xba 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 } }

-------------------------------------------------------------------------------
LiteServiceInfoMessageHandler
  onReceive Base Page Items Method
-------------------------------------------------------------------------------
../tests/tst_testliteserviceinfomessagehandler.cpp:96
...............................................................................

../3rdparty/trompeloeil/trompeloeil_catch.hpp:21: FAILED:
explicitly with message:
  No match for call of processMessage with signature void(QJsonObject) with.
    param  _1 == { 24-byte object={
   0xb0 0xbc 0x57 0x99 0xba 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 }, 24-byte object={
   0x50 0xc9 0x57 0x99 0xba 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 } }
  
  Tried liteServiceInfoHandlerMock.processMessage(messageObj) at ../tests/
  tst_testliteserviceinfomessagehandler.cpp:107
    Expected  _1 == { 24-byte object={
   0xb0 0xbc 0x57 0x99 0xba 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 }, 24-byte object={
   0x70 0xc4 0x57 0x99 0xba 0x7f 0x00 0x00 0xf0 0xc4 0x57 0x99 0xba 0x7f 0x00
  0x00
   0x50 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 } }

===============================================================================
test cases:  22 |  21 passed |  1 failed
assertions: 212 | 202 passed | 10 failed`

**Comment by evelynpenacc** [comment] 2019-01-20 01:31
Now Im able to build but I have another kind of error looks like is not able to match correctly the call 
`class LiteServiceInfoMessageHandlerMock: public LiteServiceInfoMessageHandler{
public:
    MAKE_MOCK0(requestInitialData,void(),override);
    MAKE_MOCK1(processMessage,void(QJsonObject),override);//generate error
  
};`
Test Case:
`SECTION("onReceive Base Page Items Method") {
        QJsonObject messageAction = {
            {MESSAGE_KEY_MESSAGE_TYPE,BASE_PAGE_ITEMS_METHOD},
            {MESSAGE_KEY_CALLER_ID,callerId}
        };
        QJsonObject messageObj={
            {NOTIFY_ACTION,SERVER_MESSAGE},
            {USER_INFO,messageAction}
        };
        REQUIRE_CALL(liteServiceInfoHandlerMock,processPageItems(messageObj));
        liteServiceInfoHandlerMock.setMessageHandlerTypeList();
        liteServiceInfoHandlerMock.onReceive(messageObj);
    }`
Error generated: 
`../3rdparty/trompeloeil/trompeloeil_catch.hpp:21: FAILED:
explicitly with message:
  No match for call of processPageItems with signature void(QJsonObject) with.
    param  _1 == { 24-byte object={
   0xe0 0xd2 0x4d 0xe4 0xdf 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 }, 24-byte object={
   0x20 0xd3 0x4d 0xe4 0xdf 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 } }
  
  Tried liteServiceInfoHandlerMock.processPageItems(messageObj) at ../tests/
  tst_testliteserviceinfomessagehandler.cpp:105
    Expected  _1 == { 24-byte object={
   0xe0 0xd2 0x4d 0xe4 0xdf 0x7f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
  0x00
   0x30 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 }, 24-byte object={
   0x30 0xd1 0x4d 0xe4 0xdf 0x7f 0x00 0x00 0x50 0xb3 0x4d 0xe4 0xdf 0x7f 0x00
  0x00
   0x50 0x00 0x00 0x00 0xfe 0x7f 0x00 0x00 } }

===============================================================================
test cases:  22 |  21 passed | 1 failed
assertions: 203 | 202 passed | 1 failed

20:28:52:
`

**Comment by evelynpenacc** [comment] 2019-01-20 02:05
I had fixed doing the following:
Mock class:
class LiteServiceInfoMessageHandlerMock: public LiteServiceInfoMessageHandler{
public:
    using jsonMessage = QJsonObject;//using an alias for the type
    MAKE_MOCK0(requestInitialData,void(),override);
    MAKE_MOCK1(processPageItems,void(jsonMessage),override);
};

Test Case definition:
using trompeloeil::_;
SECTION("onReceive Base Page Items Method") {

        QJsonObject messageAction = {
            {MESSAGE_KEY_MESSAGE_TYPE,BASE_PAGE_ITEMS_METHOD},
            {MESSAGE_KEY_CALLER_ID,callerId}
        };
        QJsonObject messageObj={
            {NOTIFY_ACTION,SERVER_MESSAGE},
            {USER_INFO,QJsonValue(messageAction)}
        };
        REQUIRE_CALL(liteServiceInfoHandlerMock,processPageItems(_));// match any 
        liteServiceInfoHandlerMock.setMessageHandlerTypeList();
        liteServiceInfoHandlerMock.onReceive(messageObj);
    }

**Comment by rollbear** [comment] 2019-01-20 07:30
Hmm. You may want to write a custom print function for `QJsonObject` to make it easier to see what the problem is. See https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md/#custom_formatting

It looks to me like the mock is indeed not called with the expected parameter value (the bytes in second element differs.)

Regardless, this is a different problem which deserves an issue of its own.

**Comment by rollbear** [comment] 2019-01-21 18:19
Closing this now, since the not-compiling error is fixed and included in the just tagged v33 release. Feel free to open another issue with the matching problem.

**Closed by rollbear** 2019-01-21 18:19 UTC
Labels: Fixed on master, bug
