### ISSUE TITLE
[fixed on master] compiler warning on VS2017 15.7.1

### ISSUE THREAD

**Issue by hvariant** [rollbear/trompeloeil#87] opened 2018-05-18 05:19 UTC
trompeloeil.hpp(704): warning C4355: 'this': used in base member initializer list

**Comment by rollbear** [comment] 2018-05-18 06:29
Arggg! I normally take warnings very seriously, and while I kind of can see the rationale behind this one, it's really annoying since the use here is perfectly safe. Worse yet, a solution arguably makes the code worse, and may introduce other warnings that are more severe.

I need to think about this one.

**Comment by hvariant** [comment] 2018-05-18 10:51
what's wrong with putting the initialising code in the body?

**Comment by AndrewPaxie** [comment] 2018-05-18 12:11
@hvariant : Could you post your warning level settings for your project?
Does your project treat warnings as errors?
What release of Trompeloeil were you running?

The warnings @rollbear may be concerned with is that is generally 
preferred to use initialization instead of assignment to give values to member variables
in constructors.  See: [C++ Core Guidelines, C.49](
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c49-prefer-initialization-to-assignment-in-constructors
).

I have used VS 2017 15.7.1 to run a `Debug|x64` build at `/W3` with no warning generated.
`/W4` on a local compile also produced no warnings for me.
`/Wall` produced a torrent of warnings, not just the `C4355` one you have reported.

AppVeyor ran with `/W4 /permissive-`, also with no warnings generated.
it was running `MSVC 19.13.26129.0`.

Indeed, [C4355](
https://docs.microsoft.com/en-gb/cpp/error-messages/compiler-warnings/compiler-warning-c4355
) is not enabled by default according to the VS 2017 documentation.

@rollbear: I'll send through my findings with `clang-tidy` after I have brought my working notes
up-to-date with the latest `clang-tidy` build, hopefully in the next day or so.
It may be a way to be proactive rather than reactive on issues like this.
I also have runs of JetBrains ReSharper C\+\+ in the works, but believe this work follows the changes
we may contemplate from the `clang-tidy` effort.

**Comment by hvariant** [comment] 2018-05-18 13:35
The project uses /W3 with /permissive-, but the warning only shows up in release mode. It's strange that I can't seem to reproduce the warning in a separate project, so there's probably some setting in our build process that enabled this particular warning. I'll have to take a closer look later when I have time.

We don't treat warnings as errors but there are plans to reduce the number of warnings and I don't want to introduce new warnings in my current project.

**Comment by hvariant** [comment] 2018-05-18 13:50
What's also weird is that I have several unit test projects that use trompeloeil but only one of them produces C4355...

**Comment by hvariant** [comment] 2018-05-18 14:17
oh forgot to mention I'm using the C++11 branch but the code is present in the master branch as well

**Comment by rollbear** [comment] 2018-05-18 15:38
You're not the only one who has experienced issues with MSVC release builds. See also #69, which unfortunately is not solved yet.

I don't think the C++11 branch has anything to do with this (you do know C++11 support has been on master the last two tagged releases?)

The question is how to find a solution to this without raising other warnings. As @AndrewPaxie mentioned, not initialising members in the initialiser list does leave a bit of an odour. I could default it to `nullptr` and reassign in the body, but that's just stupid (and also something that would be right to warn about.) I prefer a solution that does not stoop down to disabling warnings.

**Comment by Neargye** [comment] 2018-05-22 21:51
Another workaround [C++ Core Guidelines, C.48.](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c48-prefer-in-class-initializers-to-member-initializers-in-constructors-for-constant-initializers)
```cpp
  class tracer
  {
...
  protected:
    tracer() = default;
...
  private:
    tracer* previous = set_tracer(this);
  };
```

**Comment by AndrewPaxie** [comment] 2018-06-05 17:45
A local build incorporating @Neargye 's suggestion succeeded without generating
any warnings or errors.  I have a branch with this change,

https://github.com/AndrewPaxie/trompeloeil/commit/a09375276ec98c6066627270e8cd2125d0b26e71

[Travis build #97](
https://travis-ci.org/AndrewPaxie/trompeloeil/builds/388394287)
[AppVeyor master #9](
https://ci.appveyor.com/project/AndrewPaxie/trompeloeil/build/master%20%239)

Unfortunately, given our current tests and build configurations,
I haven't been able to reproduce the warning and therefore
cannot establish that it has been definitely resolved.

@hvariant : Would you try this in your environment and report the result?
A successful report may see this in the next tagged release.

**Comment by Neargye** [comment] 2018-06-05 19:29
@AndrewPaxie  noexcept not necessary in `tracer() noexcept = default;`  [implicit exception specification is noexcept(true)](https://en.cppreference.com/w/cpp/language/noexcept_spec)

**Comment by AndrewPaxie** [comment] 2018-06-06 11:08
Updated commit with suggestion from @Neargye .

<https://github.com/AndrewPaxie/trompeloeil/commit/33ec935021f7cc87adcec8c97db1aa3fb2be8622>

[Travis build #98](
https://travis-ci.org/AndrewPaxie/trompeloeil/builds/388697845)
Travis is running slow today, so I haven't seen the result of this build.

[AppVeyor master #11](
https://ci.appveyor.com/project/AndrewPaxie/trompeloeil/build/master%20%2311)

Note this is not all the warnings from VS resolved, particularly if `/Wall` used for
an `x86` build, but I hope this quietens down this worrisome one and buys
some time to resolve the others e.g. the C4355 in the `lifetime_monitor`
constructor when initializing `object_monitor`.

**Comment by Neargye** [comment] 2018-06-06 16:03
x32/x64 Release/Debug with /W4  [build pass](https://ci.appveyor.com/project/Neargye/trompeloeil/build/resolve_C4355%20%2348) 
https://github.com/Neargye/trompeloeil/commit/986629176dc75ad11f72ee1d0f93bc88428d0527

/Wall option gives a lot of strange warnings, including internal msvc libraries

**Comment by AndrewPaxie** [comment] 2018-06-07 06:13
I am satisfied the warning is resolved.  Pull request #92 created.

**Closed** 2018-07-23 17:44 UTC
