### ISSUE TITLE
Warning in Visual Studio Release build when mocking return structs

### ISSUE THREAD

**Issue by JohnboyJovi** [rollbear/trompeloeil#69] opened 2017-12-13 12:20 UTC
Hello, we currently try to mock OpenVR.

This works fine in general however throws an unreachable code warning in Visual Studio 2017 in Release build (not Debug). Since we have a warning==error policy, this is a problem.

The problem occusr if I add this line 
```c++
ALLOW_CALL(openvr_mock.GetSystem(), GetProjectionMatrix(_, _, _))
      .RETURN(vr::HmdMatrix44_t());
```
or any other return type where the return type is:
```c++
struct HmdMatrix44_t
{
	float m[4][4];
};
```
This seems to be related to the returning of structs, because this warning does not occur for any other of the mocked methods, retuning something else.

The warning is:
```
1>...\trompeloeil.hpp(2033): error C2220: warning treated as error - no 'object' file generated
1>...\trompeloeil.hpp(2033): warning C4702: unreachable code
```

Any ideas what could cause this, and how I could potentially circumvent it?

**Comment by rollbear** [comment] 2017-12-13 14:07
Previously unknown to me. I'll look into it. Thanks for reporting.

**Comment by rollbear** [comment] 2017-12-13 19:51
I have reproduced it now, and I mostly understand what goes wrong (I really don's see why a struct makes any difference.) Unfortunately it looks like a "damned if I do, damned if I don't" kind of situation. I added the dead default-return in order to silence warnings of missing return from non-void function.

I'll try to come up with something. Unfortunately I'm busy all day/night tomorrow, so it's Friday at the earliest. Apologies for the inconvenience.

**Comment by JohnboyJovi** [comment] 2017-12-13 21:38
Perfect, thank you very much  for looking into it.

Don't worry I implemented a workaround for now, mocking a method with another return type and then creating a method, that implements the interface and casts the return. However, would be nice to get rid of that workaround. Thank you in advance, and if I could do anything to help, let me know.

**Comment by rollbear** [comment] 2017-12-16 10:58
As I feared, this one is a bit tricky. It's easy to get rid of that warning, but it just pushes it one step further and issues a similar warning in the `trace_return` function template. I don't currently see how I can get rid of that warning. I'll continue trying.

**Comment by Neargye** [comment] 2018-05-21 08:52
@rollbear 
I tested the library in release mode, and found some warning
```cpp
line:3198
    template <typename H>
    struct throw_handler_t
    {
      using R = decltype(default_return<return_of_t<signature>>());

      throw_handler_t(H&& h_)
        : h(std::forward<H>(h_))
      {}

      template <typename T>
      R operator()(T& p)
      {
        h(p);
        return R();
      }

    private:
      H h;
    };
```

It produces an warning
```cpp
      template <typename T>
      R operator()(T& p)
      {
        h(p); // C4702 unreachable code 
        return R();
      }
```

So it is conceived that the variable  `h` is not used anywhere?

**Comment by AndrewPaxie** [comment] 2018-05-21 09:47
Was this with warning level set to `/W4`?  I don't receive C4702 at `/W3`.

Looking back at the original warning for this issue, the C4702 that you describe
is unrelated to the C4702 reported by @JohnboyJovi .

The class `throw_handler_t` was added to help with the backport to C\+\+11.
`h(p);` is intended to always `throw`, which the optimizer in MSVC appears
to have deduced, further concluding that `return R();` is now unreachable.

When this line was written as `return {};`  I received the error message
`return statement with a value in function returning void`.

Perhaps if I'd specialized `struct throw_handler_t` for `R = void` this
could all have been avoided ... .  I will see where this line of reasoning
goes and report back.  In the meantime, "help still wanted" for the
original C4702 warning.

**Comment by rollbear** [comment] 2018-05-21 11:08
I could quite easily get rid of the exact warning that was reported, but that didn't solve anything since it was just moved to another place where my attempts failed. A new pair of eyes may be what's needed, though.

**Comment by Neargye** [comment] 2018-05-21 11:30
@AndrewPaxie I test commit a98c56d38b019358ad93a6401d8481d4aeb6be58 in VS 2017 15.7.1 `/W4 /permissive-`

**Comment by Neargye** [comment] 2018-05-21 11:59
I tried to reproduce the same case, and how do I understand the warning curses this code?

```
  template <typename R>
  struct default_return_t
  {
    TROMPELOEIL_NORETURN static R value()
    {
      std::abort(); // must never be called
    }
  };

  template <typename R>
  inline
  R
  default_return()
  {
    return default_return_t<R>::value(); // C4702 unreachable code 
  }
```

**Comment by AndrewPaxie** [comment] 2018-05-22 10:43
Perhaps some progress.

I was able to silence the C4702 warnings generated in VS 2017 15.7.2,
even at `/W4 /permissive-`, for the `Release|x86` and `Release|x64` configurations,
by adding otherwise unnecessary try/catch blocks to the following functions,

```cpp
  template <
    typename Ret,
    typename F,
    typename P,
    typename = detail::enable_if_t<!std::is_void<Ret>::value>>
  Ret
  trace_return(
    trace_agent& agent,
    F& func,
    P& params)
  {
    /* Work around VS 2017 15.7.x C4702 warning by
     * enclosing the operation in an otherwise
     * unnecessary try/catch block.
     */
    try
    {
      return agent.trace_return(func(params));
    }
    catch (...)
    {
      throw;
    }
  }

  // :::

  struct throw_handler_t
  {
      // :::
      template <typename T>
      R operator()(T& p)
      {
        /* Work around VS 2017 15.7.x C4702 warning by
         * enclosing the operation in an otherwise
         * unnecessary try/catch block.
         */
        try
        {
          h(p);
        }
        catch (...)
        {
          throw;
        }
        return R();
      }
  };
```

Running regression tests now, but perhaps @rollbear, @Neargye or @JohnboyJovi 
could figure out if there are other places where this "technique" might be helpful?
It seems to me from the discussion that `default_return()` is another candidate,
which might have its function body changed to

```cpp
  try
  {
    return default_return_t<R>::value();
  }
  catch (...)
  {
    throw;
  }
```

**Comment by rollbear** [comment] 2018-05-22 12:56
I'm impressed! Yes, `default_return()` is definitely a candidate. The `void` version is expected to be called, but for any other type, it must never be called, hence the `abort()` and `NORETURN` attribute. Ideally I'd never even implement it, but then the program obviously doesn't link. If the `try`/`catch` gets rid of the warning, then please add it (unless some other compiler starts warning because of it, such is occasionally the joy of working around compiler problems.)

**Comment by Neargye** [comment] 2018-05-22 13:26
I have not yet found other places where this warning occurs.
I tried this solution myself, and it looks good for me.
What do you think about this request https://github.com/rollbear/trompeloeil/pull/89? it will help us to catch such cases in Appveyor CI.

**Comment by Neargye** [comment] 2018-05-22 14:20
@rollbear I checked the fixes @AndrewPaxie on different versions of the msvc build
https://github.com/Neargye/trompeloeil/commit/9f833acfe0720da607db69b0e6561bd49ba47719 
Result:
https://ci.appveyor.com/project/Neargye/trompeloeil/build/fix-69%20%2321
https://travis-ci.org/Neargye/trompeloeil/builds/382180502

**Comment by AndrewPaxie** [comment] 2018-05-22 19:19
@Neargye Thanks for the experimental confirmation.
I have also found my regression tests completed locally
without error.  These tests are for a broader range of
configurations that Travis or AppVeyor currently include.

I would like these changes to be scheduled before #89.
It was in my thinking that we would increase the number of
AppVeyor configurations after this warning was resolved.

@rollbear This fix goes on master?  May I commit directly given the current feedback?
@rollbear, @Neargye I will prepare the pull request with appropriate `ChangeLog`.

I have other business and a C\+\+ Meetup to attend, so there may be a few hours
delay before all the good work is realised in a push to master.

**Comment by rollbear** [comment] 2018-05-22 19:25
Go ahead and push on master, as long as it's expected to pass. No rush @AndrewPaxie .

**Comment by Neargye** [comment] 2018-05-22 19:32
@AndrewPaxie I will improve the request #89 after your edits in master.

We started using this library in addition to catch2 in our company for tests, so I'm happy to help.

**Comment by rollbear** [comment] 2018-05-22 19:34
We're very happy for your help @Neargye

**Comment by AndrewPaxie** [comment] 2018-05-23 11:21
A fix for the C4702 warnings is now on `master`.

[Travis build 478](
    https://travis-ci.org/rollbear/trompeloeil/builds/382612754
) and [AppVeyor build master 26](
    https://ci.appveyor.com/project/rollbear/trompeloeil/build/master%20%2326
) are passed.

Extended tests locally showed no warnings from  VS 2017 Release builds.

**Comment by radekvit** [comment] 2021-03-24 11:59
Unfortunately, we're getting W4702 again with Windows 10 SDK, version 2004 (10.0.19041.0).

We're able to fix it for our specific use-case by putting warning pragmas over the header file.
```
#pragma warning(push)
#pragma warning(disable : 4702)
template <typename R>
inline R default_return()
{
	return default_return_t<R>::value();
}
#pragma warning(pop)
```

**Comment by rollbear** [comment] 2021-03-24 12:24
OK.  And, of course, MSVC is currently not available on Compiler Explorer, so this might become tricky to fix.

Reading the history above, does it work if you change  the lines to:

```C++
template <typename R>
inline R default_return()
{
    try {
        return default_return_t<R>::value();
    }
    catch (...) {
        throw;
    }
}
```

In the worst case, I can add the pragmas under ifdef's, but I prefer not to if I can avoid it.

**Comment by radekvit** [comment] 2021-03-24 12:32
@rollbear That's what the function was (we got this library just a few days ago from master).
This code emits the error, unfortunately.

This started happening when we upgraded to the new SDK, on older ones this worked fine.

**Comment by rollbear** [comment] 2021-03-24 12:33
OK. Thanks.

**Comment by rollbear** [comment] 2021-04-02 13:24
Can you try this branch? https://github.com/rollbear/trompeloeil/tree/msvc_warning_suppression
I expect no problems, since it's your code filtered by `#ifdef` for MSVC compilers.

There are, unfortunately, some unrelated CI issues that I also need to look into.

**Comment by AndrewPaxie** [comment] 2021-04-02 21:54
I was hoping to find a workaround that didn't involve a warning suppression, but _c'est la vie_.

Was not able to reproduce the C4702 with the original code and various project settings in Visual Studio.  Some details of the compiler flags and other configuration options would be helpful.

**Comment by radekvit** [comment] 2021-04-02 23:37
I'm on holiday until 12. April, I'll provide additional info and try the branch when I get back to work.

**Comment by rollbear** [comment] 2021-04-04 14:50
Enjoy your time off @radekvit .

@AndrewPaxie , I have mixed feelings about work-around versus warning suppression in this case. A work around will only be successful until the compiler catches up and warns again (which seems to be what has happened here,) whereas a warning suppression for a clear case where the warning is right, but it's dead code that must be there to avoid a linking error, feels very safe. It's worse to suppress a warning in a function template where problematic user code can cause a well deserved warning.

**Comment by radekvit** [comment] 2021-04-12 10:57
@rollbear I can confirm the branch you sent me compiles fine with the new C++ SDK. Thanks!

@AndrewPaxie We use /W4 and /WX, those are the relevant settings for this warning. I believe you also need to mock some interface, and `REQUIRE_CALL` some call, with some `RETURN(some_literal)`.

**Comment by rollbear** [comment] 2021-04-14 00:03
Merged to master. So, solved, again, until the next time MSVC throws us a curve ball.

Thanks @radekvit, both for reporting and for verifying. Much appreciated.

**Comment by rollbear** [comment] 2021-04-14 00:11
BTW. @radekvit , is it of value (as in, preferably soon) for you that a new release is tagged for this? On the one hand I can see that this is an issue important enough to warrant a release, but on the other hand it's also only the silencing of a warning at extreme levels only seen on the most recent MSVC.

Tagging a new release is mostly an administrative issue, and by no means a big deal, so don't feel intimidated by the question.

**Comment by radekvit** [comment] 2021-04-16 18:29
@rollbear For us, there's no need to tag a realease because of this.

**Closed** 2021-06-15 14:07 UTC
Labels: Fixed on master
