### ISSUE TITLE
Add AppVeyor continuous integration support

### ISSUE THREAD

**Issue by AndrewPaxie** [rollbear/trompeloeil#83] opened 2018-05-05 06:29 UTC
Pull request #81, resulting in issue #82, indicates that
testing new features with **all** currently supported
compilers is the only way to provide assurance to users
that Trompeloeil does in fact compile, link, and run
with the supported compilers.

Recent features e.g. Issue #1, #73 have been released that
have fallen short of this goal.

[AppVeyor](https://www.appveyor.com/) provides the necessary
Microsoft Visual Studio compilers and GitHub integration
to provide this assurance.

Add AppVeyor support to project Trompeloeil for the following
compilers and configurations:

- Visual Studio 2015 Win64
- Visual Studio 2015
- Visual Studio 2017 Win64
- Visual Studio 2017

The compilers invoked on AppVeyor are assumed to be the latest
point releases for each version, which is that stated supported
revision level for each compiler version.
See [README.md](
https://github.com/rollbear/trompeloeil/blob/master/README.md#compiler-compatibility).

**Comment by rollbear** [comment] 2018-05-05 18:54
Indeed. To lessen the risk for future embarrassment I also added a bunch of compilers to .travis.yml, for linux and OSX.

**Comment by AndrewPaxie** [comment] 2018-05-06 08:41
In progress.

Getting `cmake` to work locally for "Visual Studio 15 2017" and "Visual Studio 15 2017 Win64"
generators first.

Sacrificed `kcov` support on Windows for now.

**Comment by rollbear** [comment] 2018-05-06 08:59
I don't think `kcov` support is important there. The coverage generated from the other runs are more than sufficient, at least as long as almost all code is common.

It might also be a good idea, later on, to look at alternative means of obtaining code coverage. I only used `kcov` because it's convenient during development, since it only requires a debug build (and also because Simon, the author, is a colleague of mine, so support was very easily available.)

**Comment by rollbear** [comment] 2018-05-06 15:38
Sounds excellent. I think that once AppVeyor integration works nicely, it should be merged into `master` ASAP, to reduce the risk that any panic-bugfix causes an uncaught regression.

**Comment by AndrewPaxie** [comment] 2018-05-07 09:13
Initial support now ready for review.
Nothing fancy, just builds four configurations and runs unit tests.

**Comment by rollbear** [comment] 2018-05-10 01:39
Man, thank you so much for your work on this

I made an attempt earlier and failed.

This'll save me/us, from losing face in the future.

4-day weekend coming up here in Swede; I'lll tag a stable version shortly.

**Comment by rollbear** [comment] 2018-05-12 06:32
As far as I can tell, this is in place now, or are there important things missing?

**Comment by AndrewPaxie** [comment] 2018-05-12 06:35
I know of nothing that would keep this open.  Time to close.

**Closed** 2018-05-12 06:35 UTC
